#!/usr/bin/env bash

filename='/home/zisis/Downloads/tranco_YJLG.csv'
#filename='/home/zisis/Desktop/Programming/domains'
n=1
while read line; 
do
   # reading each line
   echo "Line No. $n : $line"
   #IFS=', ' read -r -a array << "$line"
   IFS=',' read -ra array <<< "$line"
   echo "-----------------"
   echo "FIrst part : ${array[0]}"
   echo "SEcod part : ${array[1]}"
   echo "-----------------"
   url='https://www.'${array[1]}
   if eval /home/zisis/Desktop/Programming/curl/curl-esni '$url' 2>&1 | grep 'Configured encrypted server name (ESNI)|handshake, Finished'; then
      echo "Success Handshake with ESNI!!"
   else
      echo "Failure in Handshake!!"
   fi
done < $filename
