#!/usr/bin/env bash

filename='/home/user/zisis/data/xaa'

n=1

#variable_esni_doh=0
#variable_curl_doh=0
#variable_esni_configured=0
#variable_handshake=0

export LD_LIBRARY_PATH='/home/user/zisis/ech/openssl'

while read line; 
do
   # reading each line
   echo "Line No. $n : $line"
   #IFS=', ' read -r -a array << "$line"
   IFS=',' read -ra array <<< "$line"
   echo "########################"
   echo "------------------------"   
   echo "SEcod part : ${array[1]}"
   echo "------------------------"
   url='https://'${array[1]}
   echo "zisis... $url"
   echo "URL pinged: https://www.${array[1]}"
   variable_ech_doh=0
   variable_ech_key_doh=0
   variable_curl_doh=0
   variable_ech_configured=0
   variable_curl_handshake=0
 
   
   var=$((kdig -d @1.1.1.1 +tls-ca -t type65 ${array[1]}) 2>&1)

   key1=${var#*ech=}
   key2=${key1%% *}
   subKey=${key2% }
   echo "---- $key2"
   size=${#key2}

   echo "size of key: $size"

   if echo "$var"  | grep -E 'TLS session|status: NOERROR'; then
      variable_ech_doh=1
      if (("$size" > 50)); then
          variable_ech_key_doh=1
          echo "ECH key over DOH is fine!"
      else
          variable_ech_key_doh=0
          echo "ECH key does not exist"
      fi
   else
      variable_esni_doh=0
   fi

     
   ### Actual curl command that will be executed /// --esni-server '$url'
   #variable=$((eval /home/user/zisis/ech/curl/src/curl https://crypto.cloudflare.com --echconfig 'AEb+DQBC2AAgACDrAUfAiVH3ArBT7ekaDdclcnf1YxisidIwAXZiB7+nLwAEAAEAAQATY2xvdWRmbGFyZS1lc25pLmNvbQAA' -k --verbose) 2>&1)

   variable=$((eval /home/user/zisis/ech/curl/src/curl '$url' -k -v\
   --echconfig '$key2' -ech --doh-url 'https://1.1.1.1/dns-query') 2>&1)


   if echo "$variable" | grep -E 'a DOH request is completed'; then
      variable_curl_doh=1
      echo "Curl DOH Ok"
   else
      variable_curl_doh=0
      echo "Curl DOH Problem"
   fi

   if echo "$variable" | grep -E 'found STRING_ECH_CONFIG'; then
      variable_ech_configured=1
      echo "ECH configured Ok"
   else
      variable_ech_configured=0
      echo "ECH configuration problem"
   fi
   if echo "$variable" | grep -E 'TLS handshake, Finished|ossl_connect_step2() returning CURLE_OK'; then
      variable_curl_handshake=1
      echo "Handshake Ok"
   else
      variable_curl_handshake=0
      echo "Handshake Problem" 
   fi

   echo "Print results"
   echo ${array[0]}","$url","$variable_ech_doh","$variable_ech_key_doh","$variable_curl_doh","$variable_ech_configured","$variable_curl_handshake >> results-xaa.txt

   #if eval /home/user/zisis/ESNI/curl/curl-esni '$url' 2>&1 | grep -E 'unable to configure encrypted|Configured encrypted|handshake, Finished|failed to decode STRING_ESNI_ASCIIRR|a DOH request is completed'; then
   #   echo "Successful handshake"
   #else
   #   echo "Unknown needs examination!!"
   #fi

done < $filename
